server:
  port: 8082

#spring:
#  mail:  
#    host: smtp.gmail.com
#    username: kevensantos993@gmail.com
#    password: eyncouuxssimgwrc
#    port: 587
#          
#    properties:
#      mail:
#        smtp:
#          starttls:
#            required: true
          
spring:
  mail:
    email: campinas.ets@br.bosch.com
    host: rb-smtp-auth.rbesz01.com
    port: 25
    username: ct67ca@bosch.com
    password: <your_password>
    properties:
      mail:
        smtp:
          ssl:
            trust: rb-smtp-auth.rbesz01.com
          auth: true
          starttls:
            enable: true       
    
    
  application:
    name: email-service
   
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/email_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    






